cookietemple_version: '1.3.9 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: locatieserver
project_slug_no_hyphen: locatieserver
template_version: '2.0.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: foarsitter
creator_github_username: foarsitter
is_github_repo: true
is_repo_private: true
is_github_orga: false
full_name: Jelmer Draaijer
email: info@jelmert.nl
project_name: locatieserver
project_short_description: Locatieserver api client
version: 0.5.4
license: MIT
