# generated by datamodel-codegen:
#   timestamp: 2021-06-26T19:10:08+00:00
from __future__ import annotations

from locatieserver.schema.base import LocatieserverBaseModel


class ErrorResponse(LocatieserverBaseModel):
    metadata: list[str] | None
    msg: str
    code: int
